language: c

sudo: false

env:
  global:
    - RACKET_DIR: '~/racket'
    - GH_REF: 'github.com/lexi-lambda/racket-collections.git'
    - secure: 'nyKZY6uUXYxDjt/NcrNDBjLVRL8Ia6WYLweE59mZeNHw363e5L0fBbb0ThVX0Za51jWGCPRuANFZxIvD5S29zvCo/h3LLUvtM1PVR0YUPAKOvxjAgU0h56Bf1m8Ua61ON5Tk5O4mBTqwlKdpDW1E2w4tbkp2riLX2gqP/rHlgOBg2Af9fCCdosQu9ZayiUPqeVT4tm91p6HiY5pWcUnfbrRKwss7hylYG9d0h8qlRWvS9yfzt5BVjcKzthmpP1vPUGketgPqnWUNelnP05WJGgx9jui7gBam/XHZOWNQHGfOu9Hq0p4/mojD2xXJiv1thfsmIhR7gIWsrm4uapk7WVdt8aTNBLA9hc5izoaX6AOoB+94w5QxkqnonfTAY1SqcPY2KWTjypQ+HdIyVbuX5ZyqnXfAP3G93xEjRUgBDzI5/QiJBCLRux2Lbs++K8eTD1jy4X4lM37yUFeKYkciafQu4krW00PTHN2J0CJIjCeYMr3kS42UE53eSnEoI4Yip+oNW3n9LMxr3oiNTmY4kJOxpFYnDLRAk5lt8onS+KignvuV1CYexqdr6YCWqTJSmhGtzBhpB4gBCPPXrR1myU459t0vA0GzLr4QLgV0GKyC1nPM1XEgTZM8TdxqnGwofVlKylFNckzqHR5VY1lVDaOFJ3r6dYgni7QXrxOZ77Y='
  matrix:
    - RACKET_VERSION: 6.2
    - RACKET_VERSION: 6.2.1
    - RACKET_VERSION: 6.3
    - RACKET_VERSION: HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --deps search-auto --name collections --link $TRAVIS_BUILD_DIR
  - raco pkg install cover cover-coveralls

script:
  - raco test -p collections
  - raco cover -bf coveralls -d $TRAVIS_BUILD_DIR/coverage -p collections

after_success:
  - bash deploy-docs.sh
